// Generated by CoffeeScript 1.8.0
(function() {
  var heroes, num, nums, _i, _j, _k, _len, _len1, _len2;

  heroes = 0;

  while (heroes <= 12) {
    heroes++;
  }


  /*
  	para llevar una sentencia de control de flujo ya sea
  	una bifuracion o una iterativa se utiliza la palabra reservada
  	then
   */

  heroes = 0;

  while (heroes <= 12) {
    heroes++;
  }


  /*
  	con mayor semantica
  	La keyword until truncara el codigo es decir
  	dejara de visitar lo que existe en el fragmento 
  	de la keyword then cuando la sentencia logica a
  	su derecha se cumpla.
   */

  heroes = 0;

  while (heroes !== 12) {
    heroes++;
  }

  while (heroes !== 12) {
    heroes++;
  }

  while (!(heroes > 12)) {
    heroes++;
  }


  /*
  	----- arrays -----
  	by, when
   */

  nums = [1, 2, 3, 4, 5];

  for (_i = 0, _len = nums.length; _i < _len; _i++) {
    num = nums[_i];
    console.log(num);
  }

  for (_j = 0, _len1 = nums.length; _j < _len1; _j += 2) {
    num = nums[_j];
    console.log(num);
  }

  for (_k = 0, _len2 = nums.length; _k < _len2; _k++) {
    num = nums[_k];
    if (num % 2 === 0) {
      console.log(num);
    }
  }


  /*
  	si no se utilizan los parentesis
  	se asigna el ultimo valor calculado
  	y no el arreglo en si
   */

  nums = (function() {
    var _l, _len3, _results;
    _results = [];
    for (_l = 0, _len3 = nums.length; _l < _len3; _l++) {
      num = nums[_l];
      _results.push(num * 5);
    }
    return _results;
  })();

}).call(this);
