// Generated by CoffeeScript 1.8.0
(function() {
  var Hero, superman;

  Hero = (function() {
    function Hero(power) {
      this.power = power;
    }

    return Hero;

  })();

  superman = new Hero('Fly');

  console.log(superman.power);

}).call(this);