// Generated by CoffeeScript 1.8.0
(function() {
  var answer, born, chat, hero, now;

  hero = 'Batmam...';


  /*
  	La Interpolacion de cadenas es la introduccion de 
  	contenido dinamico en la propia cadena estatica
  	para la introduccion de ese contenido dinamico se usa la
  	siguiente sintaxis: #{ sentence_coffee }
   */

  chat = "friend : What is your favorite hero?\nsoy javi : " + hero + "\nfriend : Seriuosly? ";

  born = new Date(1980, 4, 10);

  now = new Date().getFullYear();


  /*
  	 Para realizar la interpolcaion de cadenas 
  	 la cadena tiene que tener comillas del tipo "".
  	 se permiten cualquier sentencia valida para el lenguaje 
  	 entre las llaves.
   */

  answer = "@Soyjavi was born in " + (born.getFullYear()) + ",\nnow has " + (now - born.getFullYear()) + " years old.";

  console.log(chat);

  console.log(answer);

}).call(this);
