// Generated by CoffeeScript 1.8.0

/*
	La unica diferencia aqui con js en la delcaracion de 
	objetos es el poder omitir los curly braces '{}'
	puesto que tambien se pudieron haber agregado sin errores
	en tiempo de compilacion en coffee, y tambien el
	omitir los ','
 */

(function() {
  var podcast,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  podcast = {
    number: 11,
    title: 'title',
    description: 'description',
    toString: function() {
      return "" + this.number + ", " + this.title;
    }
  };

  __indexOf.call(podcast, 'number') >= 0;

  'number' in podcast;

}).call(this);
