// Generated by CoffeeScript 1.8.0

/*
	CoffeeScript Lo Mejor De La Sintaxis De
	Ruby, Python Y Haskell
 */


/* 
	Esto Es Un Comentario 
	Multinlinea
	... Es Forsoso Que La Primera Y Ultima Linea
	Solo Tenga Los 3#
 */

(function() {
  var Year, heroe, list;

  heroe = 'Superman';

  Year = 1984;

  list = [];

  list[0] = 'Andres';

  list[1] = 'Cornejo';


  /*
  	Forma Mas Simple De Asignar
  	Cadenas En Multiples Lineas Con '\'
   */

  list[2] = 'SexoMasculino';

  list[3] = 'Calle Francisco I Madero';

}).call(this);
