// Generated by CoffeeScript 1.8.0
(function() {
  var lifes, restarGame;

  lifes = 0;

  restarGame = function() {
    return lifes = 3;
  };

  restarGame();

  console.log("I have " + lifes + " lifes in the game.");

}).call(this);
