// Generated by CoffeeScript 1.8.0
(function() {
  var lifes, restarGame;

  restarGame = function() {
    var lifes;
    return lifes = 3;
  };

  lifes = 0;

  restarGame();

  console.log("I have " + lifes + " lifes in the game.");

}).call(this);
